### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by nixonyh** [nixon-voxell/SEAJam#1]
1. Core Mechanics
- [x] Player movement and controls
- [x] #8
- [x] #3
- [x] #7
- [x] #4

2. Enemy AI
- [ ] #21
- [ ] Enemy detection of player
- [ ] ~Stun mechanic for enemies~
- [ ] change batteries when enemies are stunned

3. Level Design
- [ ] #20
- [ ] #19
- [ ] Implement interactive objects (e.g., switches, doors)
- [x] #6

4. Graphics and UI
- [ ] #22
   - Player character
   - Enemies
   - Environmental objects
   - UI elements
- [ ] #2

5. Puzzle Mechanics
- [x] #15
- [ ] Create a system for tracking puzzle completion

6. Audio
- [ ] Background music
- [ ] #23

7. Game Flow
- [ ] Implement level progression system
- [ ] Create win/lose conditions
- [ ] Design a simple menu system (start, pause, restart)

8. Optimization and Polish
- [ ] Ensure smooth performance
- [ ] Bug fixing and playtesting
- [ ] Add visual and audio feedback for player actions
